//! Build script for `termius-ui`.
//!
//! Generates a compile-time asset table from the bundled UI assets so the
//! GPUI [`AssetSource`] can serve the original Termius SVG icon set without a
//! runtime filesystem dependency (the app ships as a self-contained bundle).
//!
//! Outputs `$OUT_DIR/assets_gen.rs` with:
//! * `ICONS: &[(&str, &[u8])]` — icon path (e.g. `icons/addCircle.svg`) → bytes,
//! * `ICON_NAMES: &[&str]` — the bare icon file name (e.g. `addCircle.svg`),
//! * `FONTS: &[&[u8]]` — the embedded CircularXX faces.
//!
//! `cargo:rerun-if-changed` on both asset dirs keeps the table fresh.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn collect(dir: &Path, ext: &str) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() && path.extension().and_then(|e| e.to_str()) == Some(ext) {
            out.push(path);
        }
    }
    out.sort();
    out
}

fn rel(path: &Path, dir: &Path) -> String {
    path.strip_prefix(dir)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let icons_dir = manifest.join("assets/icons");
    let fonts_dir = manifest.join("assets/fonts");

    println!("cargo:rerun-if-changed=assets/icons");
    println!("cargo:rerun-if-changed=assets/fonts");
    println!("cargo:rerun-if-changed=build.rs");

    let icons = collect(&icons_dir, "svg");
    let fonts = collect(&fonts_dir, "ttf");

    let mut src = String::new();
    src.push_str("// @generated by termius-ui build.rs — do not edit.\n\n");

    src.push_str("/// Every bundled SVG icon: `(\"icons/<name>.svg\", bytes)`.\n");
    src.push_str("pub static ICONS: &[(&str, &[u8])] = &[\n");
    for path in &icons {
        let name = rel(path, &icons_dir);
        let key = format!("icons/{name}");
        let _ = writeln!(
            src,
            "    (\"{key}\", include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/{name}\"))),"
        );
    }
    src.push_str("];\n\n");

    src.push_str("/// Bare icon file names (e.g. `addCircle.svg`).\n");
    src.push_str("pub static ICON_NAMES: &[&str] = &[\n");
    for path in &icons {
        let name = rel(path, &icons_dir);
        let _ = writeln!(src, "    \"{name}\",");
    }
    src.push_str("];\n\n");

    src.push_str("/// The embedded UI font faces (CircularXX).\n");
    src.push_str("pub static FONTS: &[&[u8]] = &[\n");
    for path in &fonts {
        let name = rel(path, &fonts_dir);
        let _ = writeln!(
            src,
            "    include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/fonts/{name}\")),"
        );
    }
    src.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("assets_gen.rs");
    std::fs::write(&out, src).expect("write assets_gen.rs");
}
